# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessairyExpendable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
                ('quantite', models.DecimalField(decimal_places=10, max_digits=10)),
                ('lot', models.DecimalField(decimal_places=10, max_digits=10)),
                ('expDate', models.DateField()),
            ],
        ),
    ]
