# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_certificats_consommables_equipements_logistique_methodesinspections_personnels_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codClt', models.IntegerField()),
                ('raisonSocialClt', models.CharField(max_length=30)),
                ('adresseClt', models.DateField()),
                ('emailClt', models.CharField(max_length=30)),
                ('NumTelephoneClt', models.CharField(max_length=30)),
                ('webClt', models.CharField(max_length=30)),
                ('secteurClt', models.CharField(max_length=30)),
                ('serviceClt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContactsClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCntClt', models.IntegerField()),
                ('nomCntClt', models.CharField(max_length=30)),
                ('prenomCntClt', models.CharField(max_length=30)),
                ('numTelephone1CntClt', models.IntegerField()),
                ('numTelephone2CntClt', models.IntegerField()),
                ('emailCntClt', models.CharField(max_length=30)),
                ('fonctionCntClt', models.CharField(max_length=30)),
                ('codClt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Clients')),
            ],
        ),
    ]
