# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_clients_contactsclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='nomClient',
            field=models.CharField(default='ali', max_length=30),
            preserve_default=False,
        ),
    ]
