# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20180324_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCerPer', models.IntegerField()),
                ('dateObtCert', models.DateField()),
                ('dateExpirationCert', models.DateField()),
                ('organismePcert', models.CharField(max_length=30)),
                ('codCer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Certificat')),
                ('matPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='EquipementInspecter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEqp', models.IntegerField()),
                ('planifierEqp', models.CharField(max_length=30)),
                ('designationEqp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codSer', models.IntegerField()),
                ('nomSer', models.CharField(max_length=30)),
                ('typeSer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codSite', models.IntegerField()),
                ('nomSite', models.CharField(max_length=30)),
                ('typeSite', models.CharField(max_length=30)),
                ('urlSite', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WOPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='workOrdre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codWo', models.IntegerField()),
                ('numeroWo', models.CharField(max_length=30)),
                ('numeroRapportWo', models.CharField(max_length=30)),
                ('numeroCertificatWo', models.IntegerField()),
                ('numBCCltWo', models.IntegerField()),
                ('dateDebutWo', models.DateField()),
                ('dateFinWo', models.DateField()),
                ('typeInterventionWo', models.CharField(max_length=30)),
                ('sousTranitanceWo', models.CharField(max_length=30)),
                ('exigenceSpecifiqueCltWo', models.CharField(max_length=30)),
                ('exigenceHSECltWo', models.CharField(max_length=30)),
                ('CSFWo', models.CharField(max_length=30)),
                ('onSiteControleWo', models.CharField(max_length=30)),
                ('liftingWo', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='interventionTeam',
        ),
        migrations.DeleteModel(
            name='NecessairyExpendable',
        ),
        migrations.AlterField(
            model_name='contactsclient',
            name='emailCntClt',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='wopersonnel',
            name='codWo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre'),
        ),
        migrations.AddField(
            model_name='wopersonnel',
            name='matPer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Personnel'),
        ),
    ]
