# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180325_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codClt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Client')),
                ('codSite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Site')),
            ],
        ),
        migrations.CreateModel(
            name='WOConsommable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Consommable')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
            ],
        ),
        migrations.CreateModel(
            name='WOEqpInspecter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=30)),
                ('codEqp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.EquipementInspecter')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
            ],
        ),
        migrations.CreateModel(
            name='WOEquipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codEqp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Equipement')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
            ],
        ),
        migrations.CreateModel(
            name='WOlogistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.logistique')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
            ],
        ),
        migrations.CreateModel(
            name='WOMethodeInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codMethIns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.MethodesInspection')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
            ],
        ),
        migrations.CreateModel(
            name='WOService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codSer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Service')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
            ],
        ),
        migrations.CreateModel(
            name='WOVehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codWo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.workOrdre')),
                ('matVeh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vehicule')),
            ],
        ),
    ]
